import Head from 'next/head';
import Link from 'next/link';

export default function List() {
  return (
    <div>
      <Head>
        <title>List page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <img src="/images/logo.jpg" />
        <Link href="/">
          <a>home</a>
        </Link>
      </nav>
      <main>List page works</main>
    </div>
  );
}
